# adamos GDM configuration
[org/gnome/login-screen]
logo='/usr/share/images/vendor-logos/logo-adamos.png'
disable-user-list=false
disable-restart-buttons=false

[org/gnome/desktop/interface]
gtk-theme='Orchis-Dark'
icon-theme='Tela-circle-dark'
font-name='Cantarell 11'
color-scheme='prefer-dark'

[org/gnome/desktop/background]
picture-uri='file:///usr/share/backgrounds/adamos-wallpaper.png'
picture-options='zoom'
primary-color='#0d0e12'

[org/gnome/desktop/screensaver]
picture-uri='file:///usr/share/backgrounds/adamos-wallpaper.png'
primary-color='#0d0e12'

[org/gnome/desktop/session]
idle-delay=uint32 300
